class Autogenerated {
  Id iId;
  String year;
  String category;
  String overallMotivation;
  List<Laureates> laureates;

  Autogenerated(
      {this.iId,
      this.year,
      this.category,
      this.overallMotivation,
      this.laureates});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    iId = json['_id'] != null ? new Id.fromJson(json['_id']) : null;
    year = json['year'];
    category = json['category'];
    overallMotivation = json['overallMotivation'];
    if (json['laureates'] != null) {
      laureates = new List<Laureates>();
      json['laureates'].forEach((v) {
        laureates.add(new Laureates.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.iId != null) {
      data['_id'] = this.iId.toJson();
    }
    data['year'] = this.year;
    data['category'] = this.category;
    data['overallMotivation'] = this.overallMotivation;
    if (this.laureates != null) {
      data['laureates'] = this.laureates.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Id {
  String oid;

  Id({this.oid});

  Id.fromJson(Map<String, dynamic> json) {
    oid = json['$oid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['$oid'] = this.oid;
    return data;
  }
}

class Laureates {
  String id;
  String firstname;
  String surname;
  String motivation;
  String share;

  Laureates(
      {this.id, this.firstname, this.surname, this.motivation, this.share});

  Laureates.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstname = json['firstname'];
    surname = json['surname'];
    motivation = json['motivation'];
    share = json['share'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['firstname'] = this.firstname;
    data['surname'] = this.surname;
    data['motivation'] = this.motivation;
    data['share'] = this.share;
    return data;
  }
}